### ISSUE TITLE
"Mode"  not updated if changed by a hardware switch on the controller

### ISSUE THREAD

**Issue by Xnygra** [dingo35/ha-SmartEVSEv3#1]
If you have a physical switch connected to the "SW" and "GND" on the low voltage connection of the SmatEvse unit to toggle between OFF and latest used Mode (SMART, SOLAR & NORMAL) the Mode in HA is not updated. On its web page http://smartevse-XXXXX.local/ the Mode is updated and correct.

**Comment by dingo35** [comment]
Is it updated correctly at the http://smartevse-xxxxx.local/settings page?

If so, it will be updated in HA also, BUT you have to be patient, since HA only polls approx. once every 60 seconds....

**Comment by Xnygra** [comment]
Hi dingo35. Yes, you are right, it was the 60second delay that that fooled me. It works as expected. This can be closed. Thank you :)
