### ISSUE TITLE
More controls, particularly smartevse_override_current

### ISSUE THREAD

**Issue by calamarain** [dingo35/ha-SmartEVSEv3#11]
Would it be possible to add more Home Assistant controls? According to the Serkri documentation, 11 POST attributes are [available in the REST API](https://swagger-ui.serkri.be/#/Operations/updateSettings).
Particularly ```override_current```, the maximum available current, would be useful to control from Home Assistant , for instance based on the available solar power, or the power used by other devices connected to the mains.

**Comment by dingo35** [comment]
Currently override_ current is only usable in Normal Mode. So this would not only concern the integration, but would need big changes in the core of SmartEVSE firmware.

That firmware regulates the current dynamically on the mains (taking into account other power users) in Smart Mode, or the available power when generating with solar panels (in Solar Mode).
You wouldnt need HomeAssistant to do that... Why wouldnt you use those modes?

**Comment by calamarain** [comment]
I don't understand the problem with making ```override_current``` writable in any mode, even if it only has an effect in Normal Mode. That's also how the GUI works.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1917838/224508639-b6dd0cf4-749a-4a7c-9fe2-75a06151a197.png">

As I understand it, additional hardware is required to measure mains and solar power directly. But I have that information available in Home Assistant already. Or am I missing something?

**Comment by dingo35** [comment]
You can feed your HA MainsMeter info into the SmartEVSEv3 via the REST API:
https://swagger-ui.serkri.be/

Just configure your MainsMeter to EM_API.

**Comment by calamarain** [comment]
Thanks. I don't understand though why using the REST API directely is preferable to using a Home Assitant control?

**Comment by dingo35** [comment]
If you test the latest main branch you will find a slider that will set override_current in Normal Mode.

**Comment by calamarain** [comment]
Thanks!
