### ISSUE TITLE
NORMAL mode abnormally changed to SMART after Power Control switch off / swith on

### ISSUE THREAD

**Issue by negronoir** [dingo35/ha-SmartEVSEv3#13]
If Mode is set to NORMAL and you use 'SmartEVSE Power Control' switch to allow or deny charging, when you switch to 'Power off' works fine, Mode goes to OFF and charging is denied. But after that, if you switch to 'Power On' to start charging, Mode does not return to NORMAL. It is is changed to SMART (and 'no comms error' appears as no Sensorbox installed).

Seems to be some kind of error in template that doesn's store right mode retrieved from SmartEVSE and when sets whole template with new 'power control' state, also overwrites 'Normal' mode with 'Smart' value or something like that

(Firm SERKRI-1.5.3)

**Comment by dingo35** [comment]
This is intended behavior, the SMART mode is intended.
If you want to switch to any other mode you have to use the mode selector switch.

**Comment by negronoir** [comment]
Thanks for the quick answer. Ok, I've checked that switching mode NORMAL -> OFF -> NORMAL, works fine.

So problem solved. Thanks again!
