### ISSUE TITLE
Bug/Feature: Show plug icon dependent on state

### ISSUE THREAD

**Issue by jonasf21** [dingo35/ha-SmartEVSEv3#16]
The entity smartevse_car_connected has the default "eye" symbol within HA. Imho it rather should have the mdi:power-plug symbol and should be based on the BinarySensorDeviceClass.PLUG. This way it would be possible to show the correct icon (plugged or unplugged) depending on actual state.

**Comment by dingo35** [comment]
You are absolutely right; but doing this would mean to introduce a whole new device class in the integration (we now only have sensors, selects and numbers), binary sensors are not known to the plugin.

This would mean a lot of extra code; to do that just for one icon seems not worth it to me...
