### ISSUE TITLE
Improvement: Better naming policy when using multiple smartevse's

### ISSUE THREAD

**Issue by HA-TB303** [dingo35/ha-SmartEVSEv3#18]
When adding multiple smartevse's to home assistant:
![CleanShot 2023-11-30 at 16 00 14](https://github.com/dingo35/ha-SmartEVSEv3/assets/9609805/2d2bfcdf-4c97-4aa5-b951-be203e0df893)

![CleanShot 2023-11-30 at 16 00 53](https://github.com/dingo35/ha-SmartEVSEv3/assets/9609805/efd573b4-f17a-48df-bd7e-85a808de499a)

They get entities like:

![CleanShot 2023-11-30 at 16 01 43](https://github.com/dingo35/ha-SmartEVSEv3/assets/9609805/365d092b-9bdf-497e-905c-8e9c1cc80979)

This is quit confusing. It would be better if they would be added like:

sensor.smartevse_6845_access
sensor.smartevse_6847_access
sensor.smartevse_6848_access
sensor.smartevse_6849_access
etc...

Renaming 204 entities + future changes is undoable and renaming the devices, does not (bulk) change the entities.

**Comment by dingo35** [comment]
You are absolutely right; this is the result of HA not having normalized their data structure. I will look for a solution, am a bit hesitant because it will break backwards compatability...

**Comment by HA-TB303** [comment]
Understood. Hope you find a solution because renaming 204 entities is no fun :)

**Comment by HA-TB303** [comment]
For now I am using mqtt. Strangely that does support beter distinguishable naming:

![CleanShot 2024-03-19 at 14 33 47](https://github.com/dingo35/ha-SmartEVSEv3/assets/9609805/cc036550-cc65-466d-9177-9ec6e6aa4032)

![CleanShot 2024-03-19 at 14 34 15](https://github.com/dingo35/ha-SmartEVSEv3/assets/9609805/09b36007-3e28-4c2a-a466-308d8b743da5)

![CleanShot 2024-03-19 at 14 34 40](https://github.com/dingo35/ha-SmartEVSEv3/assets/9609805/7010d2ec-e1dc-442b-bc26-a8ad2ea9a984)

Maybe get the two naming policies aligned?

Thanks for your time looking into this!

**Comment by dingo35** [comment]
Im expecting a breaking change in SmartEVSE v3.5.1  and then I will address this too (since it would be breaking too).

**Comment by dingo35** [comment]
The breaking change is not happening, turns out my code is more future resistant than I thought :-) .

BUT this turns out to be a very difficult change, even ChatGPT couldn't help me out on this one. I understand you worked around it by using MQTT.

If some python/ninja2 wizzard has a PR for this I gladly will accept it...

**Comment by HA-TB303** [comment]
Yes, MQTT will do for now. :)
