### ISSUE TITLE
Please add a 'visit' link to the SmartEVSE web page

### ISSUE THREAD

**Issue by calamarain** [dingo35/ha-SmartEVSEv3#25]
So a user can easily visit the SmartEVSE's web page.

A 'visit' link like this:
<img width="288" alt="image" src="https://github.com/dingo35/ha-SmartEVSEv3/assets/1917838/75a180f4-18bf-4de8-8ca2-1d5ef73a7ab9">
(Sorry I couldn't find what this link is called or how to create it.)

**Comment by dingo35** [comment]
Im sorry but if users are too lazy to find or Google our repository... Darwin!

I can think of a dozen more interesting feature requests then this one.

**Comment by thvd** [comment]
@dingo35 I am sorry, but I think you misinterpreted this feature request. Usually this link is used to navigate to the external service, in this case the SmartEVSE dashboard. 

So it's not about this Github repo, but the SmartEVSE itself, like: 
![image](https://github.com/dingo35/ha-SmartEVSEv3/assets/973711/565be70e-60c1-4b1e-b60d-57e20df8f4f1)

**Comment by calamarain** [comment]
Sorry, I could have described that more clearly.
I do indeed mean the link to the local SmartEVSE device’s dashboard, as is common in other integrations.

**Comment by dingo35** [comment]
Same comment applies; you can derive your smartevse dns from your serial nr, it is anounced in mDNS, you can look up the ip adress in your router.
If you cant do one of these three things, IMHO you should then not build your own EV charger.

**Comment by calamarain** [comment]
I somewhat agree with your statement. 

From Home Assistant, tapping the link is more convenient than opening a browser and typing in the IP address though, especially on a phone. 
So this is purely a feature request for convenience, and common in other integrations.
