### ISSUE TITLE
HA core 2024.5.1 causing problem with mode selector

### ISSUE THREAD

**Issue by Nickdejonghe** [dingo35/ha-SmartEVSEv3#31]
Firmware SERKRI-1.8.0
After upgrade to HA core 2024.5.1 or 5.2 the command 
device_id: 13ebfd4ceffe4c4eb97c42732d788850
domain: select
entity_id: select.smartevse_mode_selector
type: select_option
option: "OFF"

fails. Mode selector remains on solar or smart. 

Restoring to HA core 2024.4.4 fixes the problem

**Comment by dingo35** [comment]
Are you sure you are interfacing with the HACS custom component ha-SmartEVSEv3 integration, and not with the MQTT integration?

**Comment by Nickdejonghe** [comment]
Yes, but I was still on v1.1.1. Just upgraded to 1.1.3 en reloaded core 5.2 and all works fine now. Thank you,NickOp 9 mei 2024 om 09:21 heeft dingo35 ***@***.***> het volgende geschreven:﻿
Are you sure you are interfacing with the HACS custom component ha-SmartEVSEv3 integration, and not with the MQTT integration?
