### ISSUE TITLE
Fix documentation regarding Serkri Firmware

### ISSUE THREAD

**Issue by jonasf21** [dingo35/ha-SmartEVSEv3#35]
Right now the project main page / readme lists:

"running version 1.5.2 or higher from the serkri firmware (https://github.com/serkri/SmartEVSE-3/releases), The original firmware has no rest-API implemented, and does not announce itself on the mDNS network, so that will not work."

This is no longer true, the default firmware now has rest-API included (apparently serkri firmware was merged into the main firmware).

**Comment by dingo35** [comment]
Thx for your report, fixed in a54e739567
