### ISSUE TITLE
Can't set charge current to max value (25A in my case)

### ISSUE THREAD

**Issue by EmanuelStassar** [dingo35/ha-SmartEVSEv3#37]
After upgrading to a 3 Phase connection, I can now use one phase for charging my 1 phase car at 25A. I changed the settings in SmartEVSE to 25A and I can see this reflected in HA. The slider control for SmartEVSE Override Current is stuck between 6 and 16A. I have not found a way to change this. It would be logical if this would be the same range as set in SmartEVSE. Can I change this in HA?

**Comment by dingo35** [comment]
-have you tried a reboot?
-if that doesnt help, please post your http://ipaddress/settings

**Comment by EmanuelStassar** [comment]
Tried a few re-boots, even set the override to 25A on the SmartEVSE web portal. HA slider still stuck between 6 and 16A.

My settings:

{"version":"v3.7.2","serialnr":6571,"mode":"OFF","mode_id":0,"car_connected":false,"wifi":{"status":"WL_CONNECTED","ssid":"Wireless-ES","rssi":-51,"bssid":"F0:2F:74:7E:16:F0"},"evse":{"temp":22,"temp_max":65,"connected":false,"access":false,"mode":0,"loadbl":0,"pwm":1024,"custombutton":false,"solar_stop_timer":0,"state":"Ready to Charge","state_id":0,"error":"EV Meter Comm Error","error_id":4,"rfid":"Ready to read card","rfid_lastread":"00000000000000"},"settings":{"charge_current":0,"override_current":95,"current_min":6,"current_max":25,"current_main":25,"current_max_circuit":25,"current_max_sum_mains":35,"max_sum_mains_time":0,"solar_max_import":2,"solar_start_current":6,"solar_stop_time":10,"enable_C2":"Not present","mains_meter":"Sensorbox","starttime":0,"stoptime":0,"repeat":0},"mqtt":{"host":"","port":1883,"topic_prefix":"SmartEVSE-15027","username":"","password_set":false,"status":"Disconnected"},"ocpp":{"mode":"Disabled","backend_url":"","cb_id":"","auth_key":"","auto_auth":"Disabled","auto_auth_idtag":"","status":"Disconnected"},"home_battery":{"current":0,"last_update":0},"ev_meter":{"description":"Sinotimer","address":20,"import_active_power":0,"total_kwh":0,"charged_kwh":0,"currents":{"TOTAL":0,"L1":0,"L2":0,"L3":0},"import_active_energy":0,"export_active_energy":0},"mains_meter":{"import_active_energy":0,"export_active_energy":0},"phase_currents":{"TOTAL":37,"L1":0,"L2":1,"L3":36,"last_data_update":1733914638,"original_data":{"TOTAL":37,"L1":0,"L2":1,"L3":36}},"backlight":{"timer":120,"status":"ON"},"color":{"off":{"R":0,"G":0,"B":0},"normal":{"R":0,"G":255,"B":0},"smart":{"R":0,"G":255,"B":0},"solar":{"R":255,"G":170,"B":0},"custom":{"R":0,"G":0,"B":255}}}

P.S. is there any way to change these settings without physical access to the SmartEVSE? I need to change the address of the Sinotimer meter to 1 but the firmware does not allow this through het button controls.

**Comment by dingo35** [comment]
Ok this is really old code, I looked it up and you are right, the 16A is a hardcoded limit in there; I wouldnt know how to get  this dynamically change to MaxCurrent (as it should be); the HomeAssistant development environment is very specific, poorly documented and unstable.

I recommend you interface through the MQTT interface of HomeAssistant, it takes some setting up but you will have much more possibilities!

**Comment by EmanuelStassar** [comment]
Thanks for the ultra quick feedback. I will have a look at using MQTT for the SmartEVSE.

**Comment by pieteroskam** [comment]
I also encounter this as an issue as of april when I bought my Nissan Leaf. The Leaf can only charge on 1 Phase max 25 amps.

**Comment by dingo35** [comment]
So you want me to repeat my advice?

**Comment by EmanuelStassar** [comment]
Adding the SmartEVSE through MQTT was easier than I expected after I found out that it needs a fix in the firmware for Smart EVSE. I found a link to that version on the SmartEVSE github page from Dingo35, so a different project by the same developer that made this integration for HA. I will search for it again and post the link here.

**Comment by dingo35** [comment]
Version v3.7.3 came out today and has the fix included!
