### ISSUE TITLE
Feature request: Adding other attributes

### ISSUE THREAD

**Issue by deqw** [dingo35/ha-SmartEVSEv3#7]
Is it possible for you to add the other attributes that are available from the SmartEVSE? When I want to use this fine integration I also have to maintain certain sensors (eg. C2, firmware version) in an other location because I am using them in my dashboard and Node-Red charging automation. Thanks!

![Screenshot 2023-02-02 at 11 34 42](https://user-images.githubusercontent.com/65849349/216302398-4236c962-3cf3-4dda-b27e-f7f8485c6a90.png)

**Comment by dingo35** [comment]
Test release v1.0.1
