### ISSUE TITLE
Unable to prepare setup for platform smartevse.switch

### ISSUE THREAD

**Issue by XanderF** [dingo35/ha-SmartEVSEv3#9]
I'm using SERKRI-1.5.3 and ha-SmartEVSEv3 v 1.0.1.

When Home Assistant is starting the following error is written to the HA log file:

Unable to prepare setup for platform smartevse.switch: Platform not found (No module named 'custom_components.smartevse.switch').

This error appeared after updating ha-SmartEVSEv3 to version 1.0.1. I think I upgraded from version 0.9.2 which did not have this issue.

**Comment by XanderF** [comment]
Also removed the integration from HA and reinstalled it. Same error.

**Comment by dingo35** [comment]
Ok if you installed via HACS you should see an update to v1.0.2 , that should fix it.

**Comment by XanderF** [comment]
Thank you. The issue is resolved.

**Comment by XanderF** [comment]
Uhm, the entire integration is now disabled. Reinstalled it, but all entities are unavailable (disabled).

**Comment by dingo35** [comment]
Yes that is probably because you are not running the latest dev version of the firmware, we had an API change there; I will make the code less dependable on the API.

**Comment by XanderF** [comment]
Ok, I'll await that version. Downgraded to 0.9 for now.

Thanks for your time and effort.

**Comment by dingo35** [comment]
Try v1.0.3

**Comment by XanderF** [comment]
Working great again. Thank you!
